library(RMassBank)
library(RMassBankData)
w <- newMsmsWorkspace()
files <- list.files(system.file('spectra', package='RMassBankData'), '.mzML', full.names=T)
w@files <- files[1:2]
loadList('./Compoundlist.csv')
loadRmbSettings('mysettings.ini')
w <- loadMsmsWorkspace('pH_narcotics.RData')
w <- msmsWorkflow(w, mode='pH', steps=8, archivename='new_archive')
mb <- newMbWorkspace(w)
mb <- resetInfolists(mb)
mb <- loadInfolists(mb, system.file("infolists", package="RMassBankData"))
mb <- mbWorkflow(mb)
